IsAggregate: false
Host: 0.0.0.0
Port: 1884
BrokerHost: "127.0.0.1"
BrokerPort: 1883
BrokerUser:
BrokerPassword:
LogFilePath: mqttsn.log
MessageQueueSize: 1000
ReadBuffSize: 212992
WriteBuffSize: 212992